const data = {
  products: [
    {
      _id: "1",
      name: "Nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Hight qulity description",
    },
    {
      _id: "2",
      name: "Nike slim shirt 1",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 130,
      brand: "Nike",
      countInStock: 10,
      rating: 2.5,
      numReviews: 5,
      description: "Hight qulity description 1",
    },
    {
      _id: "3",
      name: "Nike slim shirt 3",
      category: "pants",
      image: "/images/p3.jpg",
      price: 330,
      brand: "addidas",
      countInStock: 5,
      rating: 2.5,
      numReviews: 9,
      description: "Hight qulity description 3",
    },
    {
      _id: "4",
      name: "Nike slim shirt 4",
      category: "pants",
      image: "/images/p4.jpg",
      countInStock: 0,
      price: 160,
      brand: "addidas",
      rating: 5,
      numReviews: 15,
      description: "Hight qulity description 4",
    },
  ],
};
export default data;
